### ISSUE TITLE
Bad naming of requests: 1st time shall not be called 'failover'

### ISSUE THREAD

**Issue by vrancurel** [scality/bucketclient#25]
The first time a request is sent it shall not be logged as 'failover' but as '' (empty string).

```
failover request method=GET beginPath=/default/bucket/lpsaqwer0/969 params={} try=0
```

It is VERY confusing.

The same for sproxydclient and vaultclient.

**Comment by ThibaultRiviere** [comment]
Since we removed the failover i close this one.
